name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and push it
      run: 
        docker login --username slendymilky --password ${{ secrets.TOKEN }} ghrc.io
        docker build . --tag ghcr.io/slendymilky/ibot-gpt:latest
        docker push ghcr.io/slendymilky/ibot-gpt:latest