build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
        - uses: actions/checkout@v2 # Checking out the repo

        - name: Build and Publish latest Docker image
          uses: VaultVulp/gp-docker-action@1.1.12
          with:
              github-token: ${{ secrets.TOKEN }}
              image-name: ibot-gpt # Provide only Docker image name, tag will be automatically set to latest
              dockerfile: Dockerfile